# Generated by Django 5.1.2 on 2024-11-13 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echos', '0002_alter_echo_user'),
        ('waves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wave',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='wave',
            name='echo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waves', to='echos.echo'),
        ),
    ]
