# Generated by Django 5.1.2 on 2024-11-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='echo',
            options={'ordering': ['-created_at']},
        ),
    ]
